# Generated by Django 4.1.7 on 2023-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="updated_at",
            field=models.TimeField(auto_now=True),
        ),
    ]
